### ISSUE TITLE
Generation of components failed

### ISSUE THREAD

**Issue by stefan-riedel-seifert** [abap-openapi/abap-openapi#109]
I have a swagger 1.2 file converted by the swagger converter up to 3.0.1. So far so godd.
The old file has a section "models", which appears now in the converted file by "components".
It contain a specification of nested structures.

When i use this file, the conversion by the web frontend fails. If i remove this part the conversion succeeded, but:

i got erroneous type specification for ABAP, i.e.

  TYPES: 
     BEGIN OF ret_....,
         _200_app_json TYPE ,
     END OF ret_........ .

is this feature missing or an failure?

**Comment by stefan-riedel-seifert** [comment]
Generated artefacts also break the length specification of 30 characters

**Comment by stefan-riedel-seifert** [comment]
hmmh: something like
 _200_app;encoding=base64 TYPE string,

is not a valid type specification

**Comment by larshp** [comment]
Hi,
Can you try reducing the specification to minimum reproducing the problem, and attach it here in the issue?

**Comment by larshp** [comment]
okay, we need a minimal specification to reproduce and fix the problem

**Comment by stefan-riedel-seifert** [comment]
Okay, i will create such a spec.

**Comment by stefan-riedel-seifert** [comment]
[error_openapi.txt](https://github.com/abap-openapi/abap-openapi/files/11500038/error_openapi.txt)

**Comment by larshp** [comment]
thanks, I've pasted the txt here,

```json
{
	"openapi": "3.0.1",
	"info": {
		"version": "1.0.0"
	},
	"servers": [{
		"url": "/api/rest"
	}],
	"paths": {
		"/document": {
			"get": {
				"tags": ["tags"],
				"summary": "summary",
				"operationId": "get",
				"parameters": [{
					"name": "id",
					"in": "path",
					"description": "description",
					"required": true,
					"schema": {
						"type": "string"
					}
				}],
				"responses": {
					"200": {
						"description": "success",
						"content": {
							"*/*": {
								"schema": {
									"type": "string",
									"format": "byte"
								}
							},
							"*/*;encoding=base64": {
								"schema": {
									"type": "string",
									"format": "byte"
								}
							}
						}
					}
				}
			}
		}
	},
	"components": {
		"schemas": {
			"ccInfo": {
				"type": "object",
				"properties": {
					"email": {
						"type": "string",
						"description": "description"
					},
					"visiblePages": {
						"type": "array",
						"description": "description",
						"items": {
							"$ref": "#/components/schemas/string"
						}
					}
				}
			}
		}
	}
}
```

**Comment by larshp** [comment]
looks like the specification is not valid openapi 3,

![image](https://github.com/abap-openapi/abap-openapi/assets/5888506/0e225458-9ae7-4bbd-842c-aa09f16b8e57)

**Comment by stefan-riedel-seifert** [comment]
okay, then the swagger converter has done some things, i check this

**Comment by stefan-riedel-seifert** [comment]
Okay, my error. have to check prior before create an issue:

 a whole bunch of semantic errors :-(
 
 I have thought: swagger's own converter has no bugs

**Comment by larshp** [comment]
bugs everywhere 😅
