### ISSUE TITLE
Direct generation of ABAP Classes

### ISSUE THREAD

**Issue by OberstVonGatow** [abap-openapi/abap-openapi#114]
Hi,

first of all thank you very much for this awesome project 👍
Just wondering is it possible to generate/create the classes directly?
If i didn't missed something than right now i get the Code as String and just need to copy/paste.
That's totally fine, but as the lazy developer that I am, I'm now, of course, considering investing an inappropriate amount of time to automate it 😅

**Comment by larshp** [comment]
it can be done, but I dont like to add it, perhaps as a snippet in the docs

I'd recommend a overall setup as:
1: automated regular step(github actions or whatever CI)
2: it pulls the spec from api management(or whatever url)
3: generate the code
4: open a pull request with the code
5: normal review + unit test + change management process
6: after review pull to system via abapGit

that way you will be proactively notified of changes, updates and it passes through testing and review before hitting the system
