### ISSUE TITLE
Client Class Mapping

### ISSUE THREAD

**Issue by OberstVonGatow** [abap-openapi/abap-openapi#115]
Hi, 
i still don't really understand what the best way is to map the ABAP/JSON in the request/response.
If i look into the example it is not implemented or am i wrong?
```
METHOD zif_interface002~_test.
    DATA lv_code TYPE i.

    mi_client->request->set_method( 'POST' ).
    mi_client->request->set_data( '112233AABBCCDDEEFF' ).
    mi_client->send( ).
    mi_client->receive( ).

    mi_client->response->get_status( IMPORTING code = lv_code ).
    mi_client->response->get_data( ).
* todo
ENDMETHOD.
```

I though i need to implement it manually myself but do you have a hint what is the best way for the mapping?

(In your Example you would have the Returning Type ret__test)

**Comment by larshp** [comment]
yea, still some work to do

idea is that it generates all the boring stuff, serializing and deserializing, so the developer can focus on the actual logic

**Comment by OberstVonGatow** [comment]
So still some work to do but that is okay. Type Generation is already super handy.
I think i will start serializing/deserializing with /ui2/cl_json but maybe later switch to a ST.
(Because of [https://blogs.sap.com/2022/10/27/abap-fast-json-serialization/](https://blogs.sap.com/2022/10/27/abap-fast-json-serialization/) )
