### ISSUE TITLE
handing of multiple return values

### ISSUE THREAD

**Issue by larshp** [abap-openapi/abap-openapi#52]
eg. data returned in body and also some in header

**Comment by colbyhemond** [comment]
I believe it is also happening when multiple content types are on the same response object.
Example found in Pet store:
![image](https://user-images.githubusercontent.com/26048311/212397205-1f2132d4-b813-4ba4-b6a2-2a1ae9018c4e.png)

**Comment by colbyhemond** [comment]
@larshp, I'm currently looking into the multiple return values issue. First going off of the issue that I found in the image above.

Can you explain your example further?

> eg. data returned in body and also some in header

Additionally: I found that names cannot begin with a digit, `200 TYPE example`. Any preference on a prefix for the response code field names? `res_` maybe?

**Comment by larshp** [comment]
say, a response can be one of
* 200 with JSON
* 200 with XML
* 404 with JSON

the corresponding method should have one RETURNING parameter, typed something like

```abap
TYPES: BEGIN OF response,
200_json TYPE something1,
200_xml TYPE something2,
404_json TYPE something3,
END OF response.
```
