### ISSUE TITLE
Browser demo currently broken with error: "Loading chunk _a68d failed"

### ISSUE THREAD

**Issue by gregorwolf** [abap-openapi/abap-openapi#81]
Hello,

I've tried to run the browser demo at:

https://abap-openapi.github.io/web-openapi-client/

But see only:

```
Loading chunk _a68d failed.
(error: https://abap-openapi.github.io/web-openapi-client/_a68d.bundle.js)
```

Strange ting is that the file _a68d.bundle.js which is requested is available in https://github.com/abap-openapi/web-openapi-client.

CU
Gregor

**Comment by larshp** [comment]
@gregorwolf thanks, try again

![image](https://user-images.githubusercontent.com/5888506/195827141-9e08e811-80ae-45e9-be41-2f42d95191ca.png)

**Comment by gregorwolf** [comment]
Perfect. Thank you.
