### ISSUE TITLE
Issues with rm -rf command on windows powershell

### ISSUE THREAD

**Issue by colbyhemond** [abap-openapi/abap-openapi#89]
It appears that windows powershell doesn't support the `rm -rf` command that is used in the main scripts.

This can be fixed in 2 ways that I'm aware of:
1. Change the command to make it agnostic using something like [rimraf](https://www.npmjs.com/package/rimraf) or writing something in Node
2. Update the README to make sure users use the Bash terminal on windows, as it does support the `rm -rf` command.

@larshp let me know if you have a preference and I can work on this

**Comment by larshp** [comment]
feel free to change it to use rimraf

**Comment by colbyhemond** [comment]
Closing since PR https://github.com/abap-openapi/abap-openapi/pull/91 was merged
