### ISSUE TITLE
Interface sometimes not finding associated TYPE for response components

### ISSUE THREAD

**Issue by colbyhemond** [abap-openapi/abap-openapi#96]
Example using petstore v3 spec:
* loginuser (200 JSON, 200 XML)
* findpetsbystatus (200 XML)
* findpetsbytags (200 XML, Importing parameter `tags`)

Example where it found a TYPE for the json return component, but not the xml return component:
```abap
TYPES: BEGIN OF ret_findpetsbystatus,
           _200_app_json TYPE response_findpetsbystatus,
           _200_app_xml TYPE ,
       END OF ret_findpetsbystatus.
```

**Comment by colbyhemond** [comment]
Code that is excluding some of the xml response TYPEs https://github.com/abap-openapi/abap-openapi/blob/7a1eefddd65a23f8ffccc718272fc4651b9441c4/src/utils/zcl_oapi_references.clas.abap#L65

Related example: findpetsbystatus

**Comment by larshp** [comment]
add a folder with a testcase at https://github.com/abap-openapi/abap-openapi/tree/main/test_v2, with the simplest possible scenario to reproduce the error
